const EMBEDDED_INITIAL_DATA = {
  "equipamentos": [
    {
      "codigo": "11216",
      "descricao": "TRATOR NEW HOLLAND T7.245",
      "modelo": "NEW HOLLAND T7 240",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "BIOMASSA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11116",
      "descricao": "TRATOR NEW HOLLAND T7 245",
      "modelo": "NEW HOLLAND T7 240",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "BIOMASSA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11218",
      "descricao": "TRATOR NEW HOLLAND TL 85",
      "modelo": "NEW HOLLAND TL 85",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "BIOMASSA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11118",
      "descricao": "TRATOR NEW HOLLAND TL 85",
      "modelo": "NEW HOLLAND TL 85",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "BIOMASSA",
      "statusOS": "Com OS",
      "codOS": "767074"
    },
    {
      "codigo": "11321",
      "descricao": "NEW HOLLAND T7 240",
      "modelo": "NEW HOLLAND T7 240",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "BIOMASSA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11426",
      "descricao": "CASE PUMA 185",
      "modelo": "APLICADOR DE VINHAÇA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311517",
      "descricao": "CAMINHAO VINHACA",
      "modelo": "CAMINHÃO VINHAÇA",
      "tipo": "CAMINHÃO DE VINHAÇA",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31617",
      "descricao": "CAMINHÃO VINHAÇA",
      "modelo": "CAMINHÃO VINHAÇA",
      "tipo": "CAMINHÃO DE VINHAÇA",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "33",
      "descricao": "MOTO BOMBA CAMINHÃO",
      "modelo": "MOTO BOMBA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11616",
      "descricao": "TRATOR NEW HOLLAND T7 260",
      "modelo": "APLICADOR DE VINHAÇA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11626",
      "descricao": "CASE PUMA 185",
      "modelo": "APLICADOR DE VINHAÇA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311217",
      "descricao": "CAMINHÃO VINHACA",
      "modelo": "CAMINHÃO VINHAÇA",
      "tipo": "CAMINHÃO DE VINHAÇA",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11226",
      "descricao": "CASE PUMA 185",
      "modelo": "APLICADOR DE VINHAÇA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11316",
      "descricao": "TRATOR NEW HOLLAND T7 245",
      "modelo": "APLICADOR DE VINHAÇA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11326",
      "descricao": "CASE PUMA 185",
      "modelo": "APLICADOR DE VINHAÇA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31717",
      "descricao": "CAMINHÃO VINHACA",
      "modelo": "CAMINHÃO VINHAÇA",
      "tipo": "CAMINHÃO DE VINHAÇA",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "91",
      "descricao": "MOTO BOMBA VALETA",
      "modelo": "MOTO BOMBA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "435",
      "descricao": "MOTO BOMBA VALETA",
      "modelo": "MOTO BOMBA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "48",
      "descricao": "MASSEY FERGUSON",
      "modelo": "TRATOR DE PNEU LEVE",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11126",
      "descricao": "CASE PUMA 185",
      "modelo": "APLICADOR DE VINHAÇA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11526",
      "descricao": "CASE PUMA 185",
      "modelo": "APLICADOR DE VINHAÇA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311317",
      "descricao": "CAMINHAO VINHACA",
      "modelo": "CAMINHÃO VINHAÇA",
      "tipo": "CAMINHÃO DE VINHAÇA",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "20123",
      "descricao": "MOTO BOMBA VALETA DUPLA",
      "modelo": "MOTO BOMBA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311117",
      "descricao": "CAMINHÃO VINHAÇA",
      "modelo": "CAMINHÃO VINHAÇA",
      "tipo": "CAMINHÃO DE VINHAÇA",
      "grupo": "CAMINHOES",
      "statusOS": "Com OS",
      "codOS": "767004"
    },
    {
      "codigo": "31319",
      "descricao": "CAMINHÃO VINHAÇA",
      "modelo": "CAMINHÃO VINHAÇA",
      "tipo": "CAMINHÃO DE VINHAÇA",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "32",
      "descricao": "MOTO BOMBA CAMINHAO",
      "modelo": "MOTO BOMBA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311417",
      "descricao": "CAMINHÃO VINHACA",
      "modelo": "CAMINHÃO VINHAÇA",
      "tipo": "CAMINHÃO DE VINHAÇA",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "34",
      "descricao": "MOTO BOMBA VALETA",
      "modelo": "MOTO BOMBA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "Com OS",
      "codOS": "766828"
    },
    {
      "codigo": "11518",
      "descricao": "TRATOR NEW HOLLAND T6 - 130",
      "modelo": "NEW HOLLAND T6 - 130",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "70121",
      "descricao": "PULVERIZADOR AUTOPROPELIDO M4025",
      "modelo": "UNIPORT",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "Com OS",
      "codOS": "757748"
    },
    {
      "codigo": "11124",
      "descricao": "TRATOR CASE PUMA 155",
      "modelo": "TRATOR DE PNEU LEVE",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11718",
      "descricao": "TRATOR NEW HOLLAND T6-130",
      "modelo": "NEW HOLLAND T6 - 130",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "Com OS",
      "codOS": "764728"
    },
    {
      "codigo": "11125",
      "descricao": "TL 5",
      "modelo": "NEW HOLLAND TL5",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11224",
      "descricao": "TRATOR CASE",
      "modelo": "TRATOR DE PNEU LEVE",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "70122",
      "descricao": "UNIPORT CASE PATRIOT 250",
      "modelo": "UNIPORT",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11225",
      "descricao": "TL 5",
      "modelo": "NEW HOLLAND TL5",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11618",
      "descricao": "TRATOR NEW HOLLAND T6.130",
      "modelo": "NEW HOLLAND T6 - 130",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "340",
      "descricao": "UNIPORT VALTRA BF 3020 H",
      "modelo": "UNIPORT",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "HERBICIDA",
      "statusOS": "Com OS",
      "codOS": "766892"
    },
    {
      "codigo": "527",
      "descricao": "MOTONIVELADORA NEW HOLLAND RG 170B VHP",
      "modelo": "NEW HOLLAND RG 170B",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "329",
      "descricao": "PA CARREGADEIRA NEW HOLLAND W 170B",
      "modelo": "NEW HOLLAND W 170B",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "60118",
      "descricao": "PA CARREGADEIRA JOHN DEERE 624 K",
      "modelo": "JOHN DEERE 624 K",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "543",
      "descricao": "PA CARREGADEIRA NEW HOLLAND W130 ZB",
      "modelo": "NEW HOLLAND W 130 ZB",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "313",
      "descricao": "PA CARREGADEIRA NEW HOLLAND W 160",
      "modelo": "NEW HOLLAND W 160",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "60116",
      "descricao": "PA CARREGADEIRA JOHN DEERE 624 K",
      "modelo": "JOHN DEERE 624 K",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "60121",
      "descricao": "PA CARREGADEIRA JOHN DEERE 624 K",
      "modelo": "JOHN DEERE 624 K",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "50118",
      "descricao": "MOTONIVELADORA JOHN DEERE 670G",
      "modelo": "JOHN DEERE 670G",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "60120",
      "descricao": "PA CARREGADEIRA JHON DEERE 624 K-II",
      "modelo": "PA CARREGADEIRA JOHN DEERE 624 K-II",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "50116",
      "descricao": "MOTONIVELADORA",
      "modelo": "MOTONIVELADORA",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "60126",
      "descricao": "PA CARREGADEIRA JOHN DEERE",
      "modelo": "JOHN DEERE 624 K",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "LINHA AMARELA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "726",
      "descricao": "TRATOR NEW HOLLAND TM 7040",
      "modelo": "NEW HOLLAND TM 7040",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "732",
      "descricao": "TRATOR NEW HOLLAND TL 85",
      "modelo": "NEW HOLLAND TL 85",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11318",
      "descricao": "TRATOR NEW HOLLAND T7 175",
      "modelo": "NEW HOLLAND T7 175",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "724",
      "descricao": "TRATOR NEW HOLLAND T8-385",
      "modelo": "NEW HOLLAND T8 - 385",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11119",
      "descricao": "PREPARO",
      "modelo": "TRATORES MASSEY FERGUSON MF 283",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11221",
      "descricao": "NEW HOLLAND T7 240",
      "modelo": "NEW HOLLAND T7 240",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "Com OS",
      "codOS": "767107"
    },
    {
      "codigo": "11416",
      "descricao": "TRATOR NEW HOLLAND T7 245",
      "modelo": "PREPARO",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "Com OS",
      "codOS": "766337"
    },
    {
      "codigo": "11421",
      "descricao": "NEW HOLLAND T7 240",
      "modelo": "PREPARO",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11516",
      "descricao": "TRATOR NEW HOLLAND T7 260",
      "modelo": "NEW  HOLLAND T7 - 260",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11121",
      "descricao": "NEW HOLLAND T7 240",
      "modelo": "NEW HOLLAND T7 240",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11418",
      "descricao": "TRATOR NEW HOLLAND T6 - 130",
      "modelo": "NEW HOLLAND T6 - 130",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "418",
      "descricao": "TRATOR VALTRA BH 180 HI FLOW",
      "modelo": "VALTRA BH 180",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "PREPARO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11524",
      "descricao": "TRATOR CASE PUMA 155",
      "modelo": "TRATOR DE PNEU LEVE",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "TRATOS CULTURAIS",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11324",
      "descricao": "TRATOR CASE 155",
      "modelo": "TRATOR DE PNEU LEVE",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "TRATOS CULTURAIS",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "11424",
      "descricao": "TRATOR CASE PUMA 155",
      "modelo": "TRATOR DE PNEU LEVE",
      "tipo": "TRATOR DE PNEUS LEVES MAG100R",
      "grupo": "TRATOS CULTURAIS",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "532",
      "descricao": "TRATOR VALTRA BH 180 HI FLOW",
      "modelo": "VALTRA BH 180",
      "tipo": "Trator",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "Com OS",
      "codOS": "766961"
    },
    {
      "codigo": "535",
      "descricao": "TRATOR VALTRA BH 180 HI FLOW",
      "modelo": "VALTRA BH 180",
      "tipo": "Trator",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "537",
      "descricao": "TRATOR VALTRA BH - 180 HI FLOW",
      "modelo": "VALTRA BH 180",
      "tipo": "Trator",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "533",
      "descricao": "TRATOR VALTRA BH 180 HI FLOW",
      "modelo": "VALTRA BH 180",
      "tipo": "Trator",
      "grupo": "FERTIRRIGACAO",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31225",
      "descricao": "FH540 ALUGADO",
      "modelo": "FH540 ALUGADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80116",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8800",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80317",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8810",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "Com OS",
      "codOS": "767087"
    },
    {
      "codigo": "80224",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 9900",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80719",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8810",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80119",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8810",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80319",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8810",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "Com OS",
      "codOS": "767101"
    },
    {
      "codigo": "80419",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8810",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80219",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8810",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80320",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8800",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80316",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8000",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80217",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8810",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "Com OS",
      "codOS": "767096"
    },
    {
      "codigo": "80420",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8800",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80422",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 9900",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80322",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 9900",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80122",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 9900",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80124",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 9900",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80519",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8810",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "80120",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8800",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "Com OS",
      "codOS": "767049"
    },
    {
      "codigo": "80619",
      "descricao": "COLHEDORA",
      "modelo": "COLHEDORA CASE 8810",
      "tipo": "Colhedora",
      "grupo": "COLHEDORA",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31115",
      "descricao": "CAMINHAO CANAVIEIRO 540",
      "modelo": "PLATAFORMA TREMINHADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31125",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31215",
      "descricao": "CAMINHAO CANAVIEIRO",
      "modelo": "PLATAFORMA TREMINHADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31315",
      "descricao": "CAMINHAO CANAVIEIRO",
      "modelo": "PLATAFORMA TREMINHADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31316",
      "descricao": "CAMINHAO CANAVIEIRO",
      "modelo": "PLATAFORMA TREMINHADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31325",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31415",
      "descricao": "CAMINHAO CANAVIEIRO",
      "modelo": "PLATAFORMA TREMINHADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31425",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31515",
      "descricao": "CAMINHAO CANAVIEIRO",
      "modelo": "PLATAFORMA TREMINHADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "Com OS",
      "codOS": "766509"
    },
    {
      "codigo": "31525",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31615",
      "descricao": "CAMINHAO CANAVIEIRO",
      "modelo": "PLATAFORMA TREMINHADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31625",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31725",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31815",
      "descricao": "CAVALO MECANICO",
      "modelo": "CAMINHAO VOLVO FMX 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31825",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31915",
      "descricao": "CAVALO MECANICO",
      "modelo": "CAMINHÃO VOLVO FMX 500",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "31925",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311015",
      "descricao": "CAMINHÃO RODOTREM",
      "modelo": "CAMINHÃO VOLVO FMX 500",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311025",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "Com OS",
      "codOS": "767050"
    },
    {
      "codigo": "311115",
      "descricao": "CAMINHAO CANAVIEIRO",
      "modelo": "PLATAFORMA TREMINHADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311125",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311215",
      "descricao": "CAMINHAO CANAVIEIRO",
      "modelo": "PLATAFORMA TREMINHADO",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311225",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311325",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311425",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311525",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311625",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311725",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311825",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "311925",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    },
    {
      "codigo": "312025",
      "descricao": "CAVALO MECANICO",
      "modelo": "VOLVO FH 540",
      "tipo": "Caminhão",
      "grupo": "CAMINHOES",
      "statusOS": "OK",
      "codOS": "-"
    }
  ],
  "operacoes": [
    {
      "codigo": "4001",
      "descricao": "Corte Mecanizado De Cana Crua",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "3041",
      "descricao": "Indeterminado",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "1043",
      "descricao": "Corte Mecanizado De Mudas",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1001",
      "descricao": "Terraceamento",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1002",
      "descricao": "Terraplanagem",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1003",
      "descricao": "Conservacao De Estradas",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1005",
      "descricao": "Sistematizacao",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1006",
      "descricao": "Arranquio De Citrus",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1015",
      "descricao": "Gradagem Niveladora",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1020",
      "descricao": "Quebra De Lombo",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1027",
      "descricao": "Adubação Área",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1028",
      "descricao": "Aplicacao De Calcario",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1052",
      "descricao": "Tracao  Recolhimento De Biomassa",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1008",
      "descricao": "Arranquio De Citrus Cleopatra",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1009",
      "descricao": "Arranquio De Citrumelo",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1011",
      "descricao": "Aração",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1012",
      "descricao": "Aração Com Defensivos",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1023",
      "descricao": "Cobrição De Cana",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1029",
      "descricao": "Aplicação De Gesso",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1034",
      "descricao": "Aplicação De Compostagem",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1040",
      "descricao": "Trajeto Auxiliar de operação",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1055",
      "descricao": "Carregando - Terra - Bagaco - Outros",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1058",
      "descricao": "Aceiro Tratorizado",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1032",
      "descricao": "Aplicação de Inseticida",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1014",
      "descricao": "Gradagem Intermediaria",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1024",
      "descricao": "Enleiramento De Biomassa",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1025",
      "descricao": "Arranquio De Toco  Diversos",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1026",
      "descricao": "Aplicacao De Fosfato",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1051",
      "descricao": "Tração Para Terceiros",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1063",
      "descricao": "Apoio Pa Carregadeira",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1031",
      "descricao": "Aplicação de Herbicida",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "3071",
      "descricao": "Colhedora Disponiveis",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "1016",
      "descricao": "Subsolagem",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1018",
      "descricao": "Sulcação",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1041",
      "descricao": "Roçadeira",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1042",
      "descricao": "Rolo Compactador",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1053",
      "descricao": "Carreg Cana  Carga E Descarg",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1056",
      "descricao": "Pa Aterro De Estradas Outros",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1061",
      "descricao": "Enfardamento De Biomassa",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1062",
      "descricao": "Prest Servico Usina  Maquina",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "3063",
      "descricao": "Abastecimento De Insumos",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1068",
      "descricao": "Aplicacao De Vinhaca Localizada",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1073",
      "descricao": "Apl inseticida em profundidade",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1071",
      "descricao": "Aplicação Mista - Correção Solo",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1070",
      "descricao": "Aplicacao Mista De Produtos",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1046",
      "descricao": "Plantio de Cereais",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1080",
      "descricao": "Mapeamento Agrícola",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1076",
      "descricao": "plantio de torta",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1085",
      "descricao": "Carregamento Insumos",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1086",
      "descricao": "Limpeza De Area",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1088",
      "descricao": "Apoio Safra",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1089",
      "descricao": "Amontoando Torta",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "3029",
      "descricao": "Patio De Tratores",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "3000",
      "descricao": "Patio Barracao De Adubo",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "1035",
      "descricao": "Oficina Externa Barretos",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "1036",
      "descricao": "Oficina Externa Ribeirao Preto",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "4017",
      "descricao": "Aplic Vinhaca Caminhao",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "4018",
      "descricao": "Aplic Vinhaca Canal",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "4020",
      "descricao": "Montagem-Desmontagem Linha Vinhaca",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "3085",
      "descricao": "Aguard Encher Canal",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "2019",
      "descricao": "Trans Terra Ou Cascalho",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRANSPORTE CANA CARREGADO",
      "tempoOperacao": ""
    },
    {
      "codigo": "2023",
      "descricao": "Aguard Pa",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "1082",
      "descricao": "Carregamento de torta",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1083",
      "descricao": "Carregamento Caminhao De Terra",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1090",
      "descricao": "Repasse Aplic Herbicida",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1092",
      "descricao": "Aplic Vinhaca Com Fertilizante",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "4019",
      "descricao": "Aguard Mont Linha Vinhaca",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "3084",
      "descricao": "Transporte de Vinhaca Henriquecida",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "2020",
      "descricao": "Transp  Gesso Calcario",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "DESLOCAMENTO CARREGADO",
      "tempoOperacao": ""
    },
    {
      "codigo": "2022",
      "descricao": "Transporte De Silo",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "DESLOCAMENTO CARREGADO",
      "tempoOperacao": ""
    },
    {
      "codigo": "2018",
      "descricao": "Transp  Fertilizante",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "DESLOCAMENTO CARREGADO",
      "tempoOperacao": ""
    },
    {
      "codigo": "2024",
      "descricao": "Descarregando",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1094",
      "descricao": "Aplicacao de Fertilizante Liquido",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "3087",
      "descricao": "Carregando",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1091",
      "descricao": "Catacao Quimica",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1044",
      "descricao": "Plantio Mecanizado",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1064",
      "descricao": "Aplicacao de Fungicida",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1096",
      "descricao": "PRE PLANTIO INCORPORADO",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1095",
      "descricao": "Vigiando Cereais",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "3097",
      "descricao": "ELETRO IMA",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1105",
      "descricao": "APLI HERBICIDA EM CARREADOR",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "2006",
      "descricao": "Transp De Cana Carregado",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRANSPORTE CANA CARREGADO",
      "tempoOperacao": ""
    },
    {
      "codigo": "3051",
      "descricao": "Caminhao Carregando",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "PARADA",
      "tempoOperacao": ""
    },
    {
      "codigo": "1004",
      "descricao": "Curva Em Nivel",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1007",
      "descricao": "Arranquio De Citrus Densidade",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1022",
      "descricao": "Cultivo",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1033",
      "descricao": "Aplicacao De Torta De Filtro",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1010",
      "descricao": "Queima De Citrus",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1019",
      "descricao": "Destruição De Soqueira  Sph",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1039",
      "descricao": "Compostagem",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1054",
      "descricao": "Carreg Adubos / Herbicidas / Diversos",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1060",
      "descricao": "Perfurador De Solo",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1049",
      "descricao": "Tração",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1059",
      "descricao": "Pa Bagaço De Cana Usina",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "INATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1013",
      "descricao": "Gradagem Aradora",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1030",
      "descricao": "Aplicação Fertilizante Foliar",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1048",
      "descricao": "Serviços Curral",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1057",
      "descricao": "Esparramação De Cinzas",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "2026",
      "descricao": "Serviços Gerais de Transporte",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "2040",
      "descricao": "Carregando Cana Muda",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1081",
      "descricao": "Canterizador de Cana",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1078",
      "descricao": "Segunda Aplicacao de Herbicida",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1050",
      "descricao": "Tracao Motobomba",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1047",
      "descricao": "Silagem",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1102",
      "descricao": "SEGUNDA  APLICACAO DE VINHACA LOCALIZADA",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1084",
      "descricao": "Carregamento Torta",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1087",
      "descricao": "Limpeza De Industria",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1079",
      "descricao": "Dessecacao",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "3083",
      "descricao": "Transporte de Vinhaca Carreg",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1107",
      "descricao": "APLICACAO VIA DRENCH",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "GERAL",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "1045",
      "descricao": "CINTURANDO",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "",
      "estado": "TRABALHANDO",
      "tempoOperacao": ""
    },
    {
      "codigo": "9999",
      "descricao": "OPERAÇÃO TESTE PRODUTIVA",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "PREPARO",
      "estado": "",
      "tempoOperacao": ""
    },
    {
      "codigo": "9999",
      "descricao": "OPERAÇÃO TESTE PRODUTIVA",
      "tipoOperacao": "PRODUTIVA",
      "corporativo": "PITANGUEIRAS",
      "grupoOperacao": "Produtivas",
      "status": "ATIVO",
      "equipe": "PREPARO",
      "estado": "",
      "tempoOperacao": ""
    }
  ],
  "ordensServico": [
    {
      "tipoOS": "NORMAL",
      "subClasse": "/ -  -",
      "codigoEquip": "30601",
      "frotaCC": "30601 - 30601",
      "codOS": "734308",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "6 - OF. VOL. 41109",
      "dataEntrada": "2026-05-25T10:07:00",
      "dataPrevisao": "None",
      "diasPermanencia": "108.2",
      "descricao": "CHECK LIST",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "/ -  -",
      "codigoEquip": "30601",
      "frotaCC": "30601 - 30601",
      "codOS": "744669",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "6 - OF. VOL. 41109",
      "dataEntrada": "2026-05-25T10:07:00",
      "dataPrevisao": "None",
      "diasPermanencia": "108.2",
      "descricao": "Oficina: 6 - OF. VOLANTE 41709- F12 - CA5 Oficina: 6 - OF. VOLANTE 41709- F12 - CA5 CHECK LIST",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "/ -  -",
      "codigoEquip": "30601",
      "frotaCC": "30601 - 30601",
      "codOS": "744670",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "6 - OF. VOL. 41109",
      "dataEntrada": "2026-05-25T10:07:00",
      "dataPrevisao": "None",
      "diasPermanencia": "108.2",
      "descricao": "Oficina: 6 - OF. VOLANTE 41709- F12 - CA5 CHECK LIST",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "/ -  -",
      "codigoEquip": "30307",
      "frotaCC": "30307 - 30307",
      "codOS": "737102",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-06-03T16:15:00",
      "dataPrevisao": "2026-06-28T16:48:00",
      "diasPermanencia": "99.0",
      "descricao": "REFORMA ELEVADOR",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "/ -  -",
      "codigoEquip": "30301",
      "frotaCC": "30301 - 30301",
      "codOS": "746488",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-07-04T09:20:00",
      "dataPrevisao": "None",
      "diasPermanencia": "68.3",
      "descricao": "FAZER PEÇAS PARA USO INTERNO  FABRICAR BUCHAS TORNO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "/ -  -",
      "codigoEquip": "30401",
      "frotaCC": "30401 - 30401",
      "codOS": "747299",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-07-08T07:39:00",
      "dataPrevisao": "None",
      "diasPermanencia": "64.3",
      "descricao": "REFORMAR PORTEIRA (CASSEZI)",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "44/8 - EQUIPAMENTO - JBA / RFA / JHA - CURRAL",
      "codigoEquip": "743",
      "frotaCC": "743 - MIX-6500",
      "codOS": "751377",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-07-20T16:03:00",
      "dataPrevisao": "None",
      "diasPermanencia": "52.0",
      "descricao": "REFORMA GERAL",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "1/10 - TRATOR DE PNEUS - AUTOPROPELIDO",
      "codigoEquip": "70121",
      "frotaCC": "70121 - PULVERIZADOR JD",
      "codOS": "757748",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-08-10T07:43:00",
      "dataPrevisao": "2026-09-15T17:00:00",
      "diasPermanencia": "31.3",
      "descricao": "REFORMA  TROCAR RETROVISOR L/D VERIFICAR PARALAMA TRASEIRO L/D  VERIFICAR AMORTECEDOR DAS BARRAS E MOLAS  VERIFICAR BEXIGAO DIANTEIRO L/D  INSTALAR MANGUEIRA DE AR DENTRO DA GABINE  VERIFICAR LENTE DA SETA L/D DIANTEIRA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/8 - CAMINHOES - BASCULANTE",
      "codigoEquip": "36219",
      "frotaCC": "36219 - VOLVO VM270 6X4",
      "codOS": "760824",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-08-20T08:59:00",
      "dataPrevisao": "2026-09-15T00:00:00",
      "diasPermanencia": "21.3",
      "descricao": "REGULAR EMBREAGEM  TROCAR MOLA - DIANTEIRA L / E ( QUEBRADA )",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "44/8 - EQUIPAMENTO - JBA / RFA / JHA - CURRAL",
      "codigoEquip": "41",
      "frotaCC": "41 - VALMET 785",
      "codOS": "760891",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-08-20T13:40:00",
      "dataPrevisao": "None",
      "diasPermanencia": "21.1",
      "descricao": "SOCORRO - CURRAL  VERIFICAR PARTIDA ( NÃO PEGA )  VERIFICAR EMBREAGEM",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "13/1 - IMPLEMENTOS AGRICOLAS - CARR. DISTRIBUIDORA",
      "codigoEquip": "78220",
      "frotaCC": "78220 - SALC/APLICA",
      "codOS": "762555",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-08-25T08:40:00",
      "dataPrevisao": "None",
      "diasPermanencia": "16.3",
      "descricao": "QUEBROU CORREIA DA ESTEIRA  VERIFICAR ROSCA SEM FIM",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "1/7 - TRATOR DE PNEUS - LINHA MEDIA",
      "codigoEquip": "417",
      "frotaCC": "417 - BH 165",
      "codOS": "762860",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-08-26T18:27:00",
      "dataPrevisao": "2026-09-14T18:27:00",
      "diasPermanencia": "14.9",
      "descricao": "CAIU A PROTEÇÃO DA HÉLICE  QUEBROU A HÉLICE  ESTOUROU AS MANGUEIRAS DO RADIADOR  ESTOURO A MANGUEIRA DO ÓLEO HIDRÁULICO  ESTOUROU MANGUEIRA DO ÓLEO DIESEL",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "11/4 - VEICULOS LEVES - VEÍCULOS LEVES",
      "codigoEquip": "100318",
      "frotaCC": "100318 - SAVEIRO RB MBV",
      "codOS": "764072",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-08-29T07:33:00",
      "dataPrevisao": "None",
      "diasPermanencia": "12.4",
      "descricao": "FAZER REFORMA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "29/1 - ONIBUS - TRANSPORTE PESSOAL",
      "codigoEquip": "862",
      "frotaCC": "862 - ONIBUS M.B.",
      "codOS": "764483",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-08-31T07:46:00",
      "dataPrevisao": "2026-09-10T00:00:00",
      "diasPermanencia": "10.3",
      "descricao": "TROCAR FILTRO DO DIESEL VERIFICAR VAZAMENTO DE AGUA NO RADIADOR  VERIFICAR VAZAMENTO DE ÓLEO  AFOGA QUANDO MUDA DE MARCHA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "1/6 - TRATOR DE PNEUS - LINHA LEVE",
      "codigoEquip": "11718",
      "frotaCC": "11718 - T6.130",
      "codOS": "764728",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-01T08:00:00",
      "dataPrevisao": "2026-09-15T00:00:00",
      "diasPermanencia": "9.3",
      "descricao": "VERIFICAR TOMADA DE FORÇA CONSERTAR PINO DA PORTA  VERIFICAR ALAVANCA  DE MARCHA ( 1 E 2 MARCHA NÃO ENGATA)",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "11/4 - VEICULOS LEVES - VEÍCULOS LEVES",
      "codigoEquip": "101118",
      "frotaCC": "101118 - GOL TL.",
      "codOS": "764927",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-02T20:00:00",
      "dataPrevisao": "None",
      "diasPermanencia": "7.8",
      "descricao": "JOGANDO AGUA FORA DO RADIADOR",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "1/8 - TRATOR DE PNEUS - LINHA PESADA",
      "codigoEquip": "11416",
      "frotaCC": "11416 - T7.245",
      "codOS": "766337",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-06T10:06:00",
      "dataPrevisao": "None",
      "diasPermanencia": "4.2",
      "descricao": "QUEBROU VIDRO L/E",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/16 - CAMINHOES - MUNCK",
      "codigoEquip": "42111",
      "frotaCC": "42111 - VOLKS 24-250",
      "codOS": "766352",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-06T14:19:00",
      "dataPrevisao": "None",
      "diasPermanencia": "4.1",
      "descricao": "VERIFICAR MOLA DIANTEIRA L/E   VAZAMENTO NO CUBO  VERIFICAR MANGUEIRA DO DIFERENCIAL  VERIFICAR COMPRESSOR DE AR ( DEMORANDO PARA CARREGAR )",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/16 - CAMINHOES - MUNCK",
      "codigoEquip": "42313",
      "frotaCC": "42313 - VW 31-330 MUNCK",
      "codOS": "766358",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-06T15:24:00",
      "dataPrevisao": "None",
      "diasPermanencia": "4.0",
      "descricao": "ESTA  ASCENDENDO LUZ NO PAINEL   ESTA  AFOGANDO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "16/22 - IMPLEMENTO RODOVIARIO - REBOQUE CANAVIEIRO 4 EIXOS",
      "codigoEquip": "821922",
      "frotaCC": "821922 - RANDON 4 EIXO",
      "codOS": "766690",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-07T07:00:00",
      "dataPrevisao": "None",
      "diasPermanencia": "3.4",
      "descricao": "REFORMA LINEAR",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "16/3 - IMPLEMENTO RODOVIARIO - SEMI-REBOQUES CANAVIEIROS",
      "codigoEquip": "811922",
      "frotaCC": "811922 - SEMI RANDON 2EX",
      "codOS": "766689",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-07T07:00:00",
      "dataPrevisao": "None",
      "diasPermanencia": "3.4",
      "descricao": "REFORMA LINEAR",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "3/7 - CARREGADORAS - GUINCHO",
      "codigoEquip": "3118",
      "frotaCC": "3118 - VALTRA BM-125 I",
      "codOS": "766426",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-07T08:35:00",
      "dataPrevisao": "None",
      "diasPermanencia": "3.3",
      "descricao": "VERIFICAR PROTETOR DO CARDAN DO MOTOR",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/6 - CAMINHOES - TRANSPORTE DE CANA",
      "codigoEquip": "31515",
      "frotaCC": "31515 - VOLVO FM 540",
      "codOS": "766509",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-07T15:00:00",
      "dataPrevisao": "None",
      "diasPermanencia": "3.0",
      "descricao": "VERIFICAR CAMBIO (DANDO TRANCO)",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "16/13 - IMPLEMENTO RODOVIARIO - REBOQUE AREA DE VIVENCIA",
      "codigoEquip": "87417",
      "frotaCC": "87417 - REBOQUE AREA DE",
      "codOS": "766619",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "12 - PIT-STOP",
      "dataEntrada": "2026-09-08T06:17:00",
      "dataPrevisao": "None",
      "diasPermanencia": "2.4",
      "descricao": "REFORMA DE MELHORIA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "49/1 - TERCEIRO/PRESTADOR - TERCEIRO",
      "codigoEquip": "37055",
      "frotaCC": "37055 - IMPLEMENTO EMP",
      "codOS": "766650",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-08T08:54:00",
      "dataPrevisao": "None",
      "diasPermanencia": "2.3",
      "descricao": "COLOCAR DISCOS ( ESTA JOGADO NO PATIO )  TROCAR SUPORTE DA HASTE  VERIFICAR MOLA DO DISCOS   TROCAR BOTINHAS  VERIFICAR EMBUCHAMENTOS  COLOCAR MOLA NO ROLO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "16/10 - IMPLEMENTO RODOVIARIO - SEMI-REBOQUES BASCULANTE",
      "codigoEquip": "6143",
      "frotaCC": "6143 - SERGOMEL 3 EIXO",
      "codOS": "766652",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-08T08:55:00",
      "dataPrevisao": "None",
      "diasPermanencia": "2.3",
      "descricao": "CONSERTAR GAVIÕES DA TAMPA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "11/4 - VEICULOS LEVES - VEÍCULOS LEVES",
      "codigoEquip": "101116",
      "frotaCC": "101116 - SAVEIRO RB MBV",
      "codOS": "766655",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-08T09:05:00",
      "dataPrevisao": "None",
      "diasPermanencia": "2.3",
      "descricao": "VERIFICAR AR CONDICIONADO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/8 - CAMINHOES - BASCULANTE",
      "codigoEquip": "36119",
      "frotaCC": "36119 - VOLVO VM270 6X4",
      "codOS": "766672",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-08T10:48:00",
      "dataPrevisao": "None",
      "diasPermanencia": "2.2",
      "descricao": "VERIFICAR PARTIDA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/13 - CAMINHOES - OFICINA VOLANTE",
      "codigoEquip": "41709",
      "frotaCC": "41709 - MB-1718",
      "codOS": "762125",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-08T11:39:00",
      "dataPrevisao": "None",
      "diasPermanencia": "2.2",
      "descricao": "VERIFICAR COMPRESSOR DE AR ( NÃO CARREGA )  VERIFICAR PINO DE CENTRO L / E",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "48/68 - QUADRICICULO - QUADRICICULO",
      "codigoEquip": "2220",
      "frotaCC": "2220 - TRX 420 4X4",
      "codOS": "766722",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-08T15:24:00",
      "dataPrevisao": "None",
      "diasPermanencia": "2.0",
      "descricao": "TROCAR RETROVISORES   VERIFICAR VAZAMENTO NO TANQUE DE VENENO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "16/9 - IMPLEMENTO RODOVIARIO - REBOQUE PRANCHA",
      "codigoEquip": "5517",
      "frotaCC": "5517 - SERGOMEL 2 EIXO",
      "codOS": "766729",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-08T16:29:00",
      "dataPrevisao": "None",
      "diasPermanencia": "2.0",
      "descricao": "APERTAR GRAMPO DO FEIXE DE MOLA - SEGUDNO EIXO L/D -",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/9 - CAMINHOES - BOMBEIROS",
      "codigoEquip": "38221",
      "frotaCC": "38221 - VOLVO VM270 6X4",
      "codOS": "738623",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-09T02:47:00",
      "dataPrevisao": "None",
      "diasPermanencia": "1.6",
      "descricao": "EMBREAGEM QUBRADA VAZAMENTO NO TANQUE DAGUA VERIFICAR LANTERNA DO L/D  VERIFICAR LUZ DE FREIO SUPORTE QUEBRADO - COMANDO SAIDA DE AR  APERTAR PARAFUSO DAS RODAS DIANTIERAS E TRASEIRAS  CARRETEL DA MANGUEIRA DESACOPLOU DO MANCAL - ROSCA INTERNA TROCAR LUZ DA CABINE VERIFICAR VAZAMENTO NA MANGUEIRA DE AR EQUIPAMENTO CAINDO EM NEUTRO TROCAR TOMADA DE FORÇA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "42/1 - MOTOR ESTACIONÁRIO - MOTOBOMBA VINHAÇA",
      "codigoEquip": "34",
      "frotaCC": "34 - MOTOBOMBA",
      "codOS": "766828",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-09T07:33:00",
      "dataPrevisao": "None",
      "diasPermanencia": "1.4",
      "descricao": "VERIFICAR MOTOR DE PARTIDA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "1/10 - TRATOR DE PNEUS - AUTOPROPELIDO",
      "codigoEquip": "340",
      "frotaCC": "340 - BS-3020 H",
      "codOS": "766892",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-09T11:40:00",
      "dataPrevisao": "None",
      "diasPermanencia": "1.2",
      "descricao": "VERIFICAR PARTE ELETRICA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "16/22 - IMPLEMENTO RODOVIARIO - REBOQUE CANAVIEIRO 4 EIXOS",
      "codigoEquip": "82924",
      "frotaCC": "82924 - SERGOMEL 4 EIXO",
      "codOS": "766933",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "12 - PIT-STOP",
      "dataEntrada": "2026-09-09T16:01:00",
      "dataPrevisao": "None",
      "diasPermanencia": "1.0",
      "descricao": "FAZER SUPORTE DAS CORRENTES SERVIÇO DE CALDEIRARIA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "1/7 - TRATOR DE PNEUS - LINHA MEDIA",
      "codigoEquip": "532",
      "frotaCC": "532 - BH-180 HI FLOW",
      "codOS": "766961",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-09T20:03:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.8",
      "descricao": "COLOCAR VIDRO FRONTAL ( QUEBRADO ) VERIFICAR ACELERADOR (TRAVANDO QUANDO DESACELERA) VERIFICAR VEDAÇÃO NO SISTEMA DE AR (VAZAMENTO QUANDO CHOVE)",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "11/2 - VEICULOS LEVES - CAMIONETES",
      "codigoEquip": "100112",
      "frotaCC": "100112 - S 10 LTZ",
      "codOS": "766992",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "178 - MANUT. CAMPO",
      "dataEntrada": "2026-09-10T00:37:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.6",
      "descricao": "AFOGOU E NÃO PEGA PARTIDA  LOCAL: ELETRICA INDUSTRIA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/9 - CAMINHOES - BOMBEIROS",
      "codigoEquip": "38121",
      "frotaCC": "38121 - VOLVO VM270 6X4",
      "codOS": "764348",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T01:35:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.6",
      "descricao": "COLOCAR CARRETEL DE MAGUEIRA COLOCAR MANGUEIRA (ESTA UTILIZANDO SOMENTE O CANHAO) PERDENDO FORÇA E FUMACIANDO MUITO  CANO DO COMPRESSOR FURADO -  TÁ DESCARREGANDO O AR  DA EMBREAGEM   LOCAL: FRENTE 10 - DESCEU PARA OFICINA 10/09 AS 01:35",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/23 - CAMINHOES - TRANSPORTE DE VINHAÇA",
      "codigoEquip": "311117",
      "frotaCC": "311117 - VOLVO FM 500",
      "codOS": "767004",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "178 - MANUT. CAMPO",
      "dataEntrada": "2026-09-10T04:29:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.5",
      "descricao": "SOCORRO - LOCAL : CARREGAMENTO DE VINHAÇA  AFOGOU ENGATADO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "1/7 - TRATOR DE PNEUS - LINHA MEDIA",
      "codigoEquip": "531",
      "frotaCC": "531 - BH-205 HI FLOW",
      "codOS": "767022",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T08:08:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.3",
      "descricao": "REFORMA LINEAR",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/9 - CAMINHOES - BOMBEIROS",
      "codigoEquip": "698",
      "frotaCC": "698 - VW 26260 BOMB",
      "codOS": "767040",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T09:20:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.3",
      "descricao": "VERIFICAR PARAFUSO DE RODA TRASEIRO  L / E",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "16/3 - IMPLEMENTO RODOVIARIO - SEMI-REBOQUES CANAVIEIROS",
      "codigoEquip": "81624",
      "frotaCC": "81624 - SEMI SERG. 2 EX",
      "codOS": "767114",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "12 - PIT-STOP",
      "dataEntrada": "2026-09-10T10:00:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.3",
      "descricao": "VERIFICAR SAPATA   VERIFICAR PINO DE CENTRO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "14/1 - COLHEDORA - COLHEDORA DE CANA PICADA",
      "codigoEquip": "80120",
      "frotaCC": "80120 - CASE A 8810",
      "codOS": "767049",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "4 - OF. VOL. 41409",
      "dataEntrada": "2026-09-10T10:10:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.2",
      "descricao": "VERIFICAR TREM DE ROLO ( NÃO ENGOLE CANA )  VERIFICAR VAZAMENTO NA MANGUEIRA DA CAIXA DE BOMBAS",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/1 - CAMINHOES - CAVALO MECANICO",
      "codigoEquip": "311025",
      "frotaCC": "311025 - FH540 ALUGADO",
      "codOS": "767050",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T10:10:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.2",
      "descricao": "VERIFICAR SUPORTE DO PARALAMA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/11 - CAMINHOES - BORRACHEIRO",
      "codigoEquip": "42105",
      "frotaCC": "42105 - VW 31-310 MUNCK",
      "codOS": "767065",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T10:18:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.2",
      "descricao": "SOCORRO - EUCALIPTO CHEIROSO  AFOGOU E NÃO PEGA  VERIFICAR RESERVATORIO DE AGUA ( FURADO )  COLOCAR PARAFUSO DO ESTIRANTE   COLOCAR PORCA NO AMORTECEDOR DINATEIRO L / D   VERIFICAR FREIO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "1/6 - TRATOR DE PNEUS - LINHA LEVE",
      "codigoEquip": "11118",
      "frotaCC": "11118 - TL 85",
      "codOS": "767074",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T11:15:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.2",
      "descricao": "VERIFICAR REGULAGEM DO BANCO   VERIFICAR REGULAGEM DO VOLANTE   VERIFICAR EMBREAGEM",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "13/1 - IMPLEMENTOS AGRICOLAS - CARR. DISTRIBUIDORA",
      "codigoEquip": "408",
      "frotaCC": "408 - DIST. CAL/TORTA",
      "codOS": "767082",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T12:04:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.2",
      "descricao": "AUMENTAR CARDAN",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "10/67 - CAMINHOES - COLETA DE LIXO",
      "codigoEquip": "618",
      "frotaCC": "618 - CARGO 2425",
      "codOS": "767083",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "178 - MANUT. CAMPO",
      "dataEntrada": "2026-09-10T12:22:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.2",
      "descricao": "SOCORRO - BARRACÃO DE RESIDUOS   VERIFICAR PARTIDA ( NÃO PEGA )",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "14/1 - COLHEDORA - COLHEDORA DE CANA PICADA",
      "codigoEquip": "80317",
      "frotaCC": "80317 - CASE A 8810",
      "codOS": "767087",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T12:44:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.1",
      "descricao": "VERIFICAR ELEVADOR  VERIFICAR FUNCIONAMENTO DO MOTOR  VERIFICAR DIVISOR DE LINHA",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "13/23 - IMPLEMENTOS AGRICOLAS - SUBSOLADOR",
      "codigoEquip": "843",
      "frotaCC": "843 - SUBSOLADOR",
      "codOS": "767092",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "178 - MANUT. CAMPO",
      "dataEntrada": "2026-09-10T13:34:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.1",
      "descricao": "SOCORRO - CASA VEIA (LUSITANIA)  QUEBROU ROLAMENTO DO DISCO CORTANTE",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "14/1 - COLHEDORA - COLHEDORA DE CANA PICADA",
      "codigoEquip": "80217",
      "frotaCC": "80217 - CASE A 8810",
      "codOS": "767096",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "7 - OF. VOL. 41102",
      "dataEntrada": "2026-09-10T13:53:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.1",
      "descricao": "VERIFICAR AR CONDICIONADO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "14/1 - COLHEDORA - COLHEDORA DE CANA PICADA",
      "codigoEquip": "80319",
      "frotaCC": "80319 - CASE A 8810",
      "codOS": "767101",
      "statusOS": "ABERTA",
      "tipoOficina": "CAMPO",
      "oficina": "5 - OF. VOL. 41105",
      "dataEntrada": "2026-09-10T14:30:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.1",
      "descricao": "TROCAR BOJO DO PRIMARIO  VERIFICAR ESTEIRA RODANTE",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "16/19 - IMPLEMENTO RODOVIARIO - REBOQUE VINHAÇA",
      "codigoEquip": "5134",
      "frotaCC": "5134 - SERGOMEL 2 EIXO",
      "codOS": "765868",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "231 - LUB. LAV. VEICULOS",
      "dataEntrada": "2026-09-10T14:37:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.1",
      "descricao": "GERADA PELA GERAÇÃO DE O.S. EM LOTE - LAVAR LAVADOR PROGRAMADA - 2026/37",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "44/4 - EQUIPAMENTO - JBA / RFA / JHA - CARROS LEVES",
      "codigoEquip": "553",
      "frotaCC": "553 - F-1000",
      "codOS": "767103",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "231 - LUB. LAV. VEICULOS",
      "dataEntrada": "2026-09-10T14:46:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.1",
      "descricao": "LAVAR",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "11/4 - VEICULOS LEVES - VEÍCULOS LEVES",
      "codigoEquip": "100118",
      "frotaCC": "100118 - VOYAGE",
      "codOS": "767106",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T14:57:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.0",
      "descricao": "VERIFICAR RADIADOR ( SOLTO )",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "1/8 - TRATOR DE PNEUS - LINHA PESADA",
      "codigoEquip": "11221",
      "frotaCC": "11221 - NW T7 240",
      "codOS": "767107",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "1 - OF. CENTRAL",
      "dataEntrada": "2026-09-10T15:00:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.0",
      "descricao": "VERIFICAR VAZAMENTO DE OLEO HIDRAULICO ( EMBAIXO DA CABINE )",
      "dataSincronizacao": "2026-09-10 15:53:34"
    },
    {
      "tipoOS": "NORMAL",
      "subClasse": "54/1 - BOMBA D'ÁGUA - LAVADOR",
      "codigoEquip": "26002",
      "frotaCC": "26002 - BOMBA D'ÁGUA LA",
      "codOS": "767111",
      "statusOS": "ABERTA",
      "tipoOficina": "INTERNA",
      "oficina": "231 - LUB. LAV. VEICULOS",
      "dataEntrada": "2026-09-10T15:30:00",
      "dataPrevisao": "None",
      "diasPermanencia": "0.0",
      "descricao": "VERIFICAR  OLEO",
      "dataSincronizacao": "2026-09-10 15:53:34"
    }
  ],
  "adminConfig": {
    "customGroups": {
      "11216": "BIOMASSA",
      "311517": "FERTIRRIGACAO",
      "31617": "FERTIRRIGACAO",
      "33": "FERTIRRIGACAO",
      "311217": "FERTIRRIGACAO",
      "31717": "FERTIRRIGACAO",
      "311317": "FERTIRRIGACAO",
      "311117": "FERTIRRIGACAO",
      "31319": "FERTIRRIGACAO",
      "32": "FERTIRRIGACAO",
      "311417": "FERTIRRIGACAO"
    },
    "customTypes": {
      "313": "Pá carregadeira",
      "329": "Pá carregadeira",
      "527": "Motoniveladora",
      "543": "Pá carregadeira",
      "50116": "Motoniveladora",
      "50118": "Motoniveladora",
      "60116": "Pá carregadeira",
      "60118": "Pá carregadeira",
      "60120": "Pá carregadeira",
      "60121": "Pá carregadeira",
      "60126": "Pá carregadeira"
    },
    "customOps": {
      "11216": "1061 - Enfardamento De Biomassa",
      "11116": "1061 - Enfardamento De Biomassa",
      "11218": "1024 - Enleiramento De Biomassa",
      "11118": "1024 - Enleiramento De Biomassa",
      "11321": "5003 - Recolhimento de Biomassa",
      "11426": "1068 - Aplicacao De Vinhaca Localizada",
      "311517": "3083 - Transporte de Vinhaca Carreg",
      "31617": "3083 - Transporte de Vinhaca Carreg",
      "33": "1040 - Trajeto Auxiliar de operação",
      "11616": "1068 - Aplicacao De Vinhaca Localizada",
      "11626": "1068 - Aplicacao De Vinhaca Localizada",
      "311217": "3083 - Transporte de Vinhaca Carreg",
      "11226": "1068 - Aplicacao De Vinhaca Localizada",
      "11316": "1068 - Aplicacao De Vinhaca Localizada",
      "11326": "1068 - Aplicacao De Vinhaca Localizada",
      "31717": "3083 - Transporte de Vinhaca Carreg",
      "91": "4018 - Aplic Vinhaca Canal",
      "435": "4018 - Aplic Vinhaca Canal",
      "48": "1040 - Trajeto Auxiliar de operação",
      "11126": "1068 - Aplicacao De Vinhaca Localizada",
      "11526": "1068 - Aplicacao De Vinhaca Localizada",
      "311317": "4018 - Aplic Vinhaca Canal",
      "20123": "4018 - Aplic Vinhaca Canal",
      "311117": "3083 - Transporte de Vinhaca Carreg",
      "31319": "3083 - Transporte de Vinhaca Carreg",
      "32": "4018 - Aplic Vinhaca Canal",
      "311417": "3083 - Transporte de Vinhaca Carreg",
      "34": "4018 - Aplic Vinhaca Canal",
      "532": "1040 - Trajeto Auxiliar de operação",
      "535": "1040 - Trajeto Auxiliar de operação",
      "537": "1040 - Trajeto Auxiliar de operação",
      "533": "1040 - Trajeto Auxiliar de operação",
      "80116": "4001 - Corte Mecanizado De Cana Crua",
      "80317": "4001 - Corte Mecanizado De Cana Crua",
      "80224": "4001 - Corte Mecanizado De Cana Crua",
      "80719": "4001 - Corte Mecanizado De Cana Crua",
      "80119": "4001 - Corte Mecanizado De Cana Crua"
    },
    "customOpTeams": {
      "3025": "PREPARO",
      "3003": "PREPARO",
      "3004": "PREPARO",
      "3005": "PREPARO",
      "3006": "PREPARO",
      "3007": "PREPARO",
      "3008": "PREPARO",
      "3010": "PREPARO",
      "3011": "PREPARO",
      "3012": "TRATOS CULTURAIS",
      "3013": "TRATOS CULTURAIS",
      "3014": "PREPARO",
      "3015": "PREPARO",
      "3016": "PREPARO",
      "3017": "PREPARO",
      "3018": "PREPARO",
      "3020": "PREPARO",
      "3021": "BIOMASSA",
      "3022": "PREPARO",
      "3023": "PREPARO",
      "3026": "PREPARO",
      "3028": "PREPARO",
      "3030": "PREPARO",
      "3032": "PREPARO",
      "3033": "PREPARO",
      "4001": "COLHEDORA",
      "4002": "COLHEDORA",
      "3036": "PREPARO",
      "3037": "PREPARO",
      "3038": "PREPARO",
      "3043": "PREPARO",
      "3044": "PREPARO",
      "3046": "PREPARO",
      "3047": "BIOMASSA",
      "3002": "PREPARO",
      "3034": "PREPARO",
      "3048": "PREPARO",
      "3050": "PREPARO",
      "3057": "PREPARO",
      "3058": "PREPARO",
      "3060": "BIOMASSA",
      "4005": "PREPARO",
      "4008": "BIOMASSA",
      "4009": "BIOMASSA",
      "4011": "BIOMASSA",
      "4012": "BIOMASSA",
      "4014": "BIOMASSA",
      "2007": "BIOMASSA",
      "2031": "BIOMASSA",
      "2032": "BIOMASSA",
      "3052": "PREPARO",
      "3053": "BIOMASSA",
      "3054": "BIOMASSA",
      "3055": "BIOMASSA",
      "3009": "PREPARO",
      "3040": "PREPARO",
      "3041": "PREPARO",
      "3061": "PREPARO",
      "1043": "BIOMASSA",
      "3001": "PREPARO",
      "3039": "PREPARO",
      "3065": "PREPARO",
      "3068": "PREPARO",
      "3062": "PREPARO",
      "3064": "PREPARO",
      "3067": "LINHA AMARELA",
      "3069": "PREPARO",
      "3070": "PREPARO",
      "1001": "PREPARO",
      "1002": "LINHA AMARELA",
      "1003": "LINHA AMARELA",
      "1005": "LINHA AMARELA",
      "1006": "TRATOS CULTURAIS",
      "1015": "PREPARO",
      "1020": "PREPARO",
      "1027": "FERTIRRIGACAO",
      "1028": "FERTIRRIGACAO",
      "1052": "BIOMASSA",
      "1008": "TRATOS CULTURAIS",
      "1009": "TRATOS CULTURAIS",
      "1011": "PREPARO",
      "1012": "HERBICIDA",
      "1023": "PREPARO",
      "1029": "FERTIRRIGACAO",
      "1034": "FERTIRRIGACAO",
      "1040": "PREPARO",
      "1055": "PREPARO",
      "1058": "PREPARO",
      "1032": "HERBICIDA",
      "1014": "PREPARO",
      "1024": "BIOMASSA",
      "1025": "PREPARO",
      "1026": "FERTIRRIGACAO",
      "1051": "PREPARO",
      "1063": "PREPARO",
      "1031": "HERBICIDA",
      "3071": "PREPARO",
      "1016": "PREPARO",
      "1018": "PREPARO",
      "1041": "TRATOS CULTURAIS",
      "1042": "LINHA AMARELA",
      "1053": "PREPARO",
      "1056": "LINHA AMARELA",
      "1061": "BIOMASSA",
      "1062": "PREPARO",
      "3063": "FERTIRRIGACAO",
      "1068": "FERTIRRIGACAO",
      "5001": "HERBICIDA",
      "1072": "FERTIRRIGACAO",
      "5006": "FERTIRRIGACAO",
      "3072": "PREPARO",
      "3066": "BIOMASSA",
      "5003": "HERBICIDA",
      "5005": "HERBICIDA",
      "1245": "LINHA AMARELA",
      "5002": "PREPARO",
      "3073": "PREPARO",
      "4899": "PREPARO",
      "1073": "HERBICIDA",
      "1071": "FERTIRRIGACAO",
      "1070": "FERTIRRIGACAO",
      "3076": "PREPARO",
      "1074": "TRATOS CULTURAIS",
      "3074": "PREPARO",
      "6001": "PREPARO",
      "6002": "PREPARO",
      "6004": "FERTIRRIGACAO",
      "3075": "PREPARO",
      "3077": "PREPARO",
      "3081": "PREPARO",
      "3078": "PREPARO",
      "1046": "TRATOS CULTURAIS",
      "1080": "PREPARO",
      "3080": "PREPARO",
      "1076": "FERTIRRIGACAO",
      "3082": "PREPARO",
      "1085": "PREPARO",
      "1086": "LINHA AMARELA",
      "1088": "PREPARO",
      "1089": "FERTIRRIGACAO",
      "3029": "PREPARO",
      "3000": "PREPARO",
      "1035": "PREPARO",
      "1036": "PREPARO",
      "4017": "FERTIRRIGACAO",
      "4018": "FERTIRRIGACAO",
      "4020": "FERTIRRIGACAO",
      "3085": "-",
      "2019": "PREPARO",
      "2023": "PREPARO",
      "1082": "FERTIRRIGACAO",
      "6005": "FERTIRRIGACAO",
      "3088": "PREPARO",
      "1083": "LINHA AMARELA",
      "4015": "BIOMASSA",
      "1090": "HERBICIDA",
      "1092": "FERTIRRIGACAO",
      "4019": "FERTIRRIGACAO",
      "3084": "FERTIRRIGACAO",
      "3086": "PREPARO",
      "2020": "FERTIRRIGACAO",
      "2022": "PREPARO",
      "2018": "FERTIRRIGACAO",
      "2024": "PREPARO",
      "1094": "FERTIRRIGACAO",
      "3087": "FERTIRRIGACAO",
      "1091": "HERBICIDA",
      "4021": "BIOMASSA",
      "4023": "PREPARO",
      "1044": "TRATOS CULTURAIS",
      "3089": "TRATOS CULTURAIS",
      "3090": "PREPARO",
      "4024": "FERTIRRIGACAO",
      "1064": "HERBICIDA",
      "3091": "PREPARO",
      "3092": "PREPARO",
      "1096": "TRATOS CULTURAIS",
      "1095": "PREPARO",
      "3094": "PREPARO",
      "2017": "PREPARO",
      "2042": "FERTIRRIGACAO",
      "1038": "PREPARO",
      "3093": "PREPARO",
      "3095": "PREPARO",
      "3096": "PREPARO",
      "3097": "PREPARO",
      "1105": "HERBICIDA",
      "3024": "PREPARO",
      "3027": "PREPARO",
      "3031": "PREPARO",
      "4003": "BIOMASSA",
      "2006": "BIOMASSA",
      "3042": "PREPARO",
      "3045": "PREPARO",
      "4007": "PREPARO",
      "3035": "PREPARO",
      "3056": "PREPARO",
      "3059": "PREPARO",
      "4006": "BIOMASSA",
      "4010": "BIOMASSA",
      "4013": "BIOMASSA",
      "2030": "BIOMASSA",
      "3051": "BIOMASSA",
      "1004": "PREPARO",
      "1007": "TRATOS CULTURAIS",
      "1022": "TRATOS CULTURAIS",
      "1033": "FERTIRRIGACAO",
      "1069": "PREPARO",
      "1010": "TRATOS CULTURAIS",
      "1019": "PREPARO",
      "1039": "PREPARO",
      "1054": "HERBICIDA",
      "1060": "BIOMASSA",
      "1017": "PREPARO",
      "1049": "PREPARO",
      "1059": "PREPARO",
      "1013": "PREPARO",
      "1030": "FERTIRRIGACAO",
      "1048": "TRATOS CULTURAIS",
      "1057": "PREPARO",
      "2026": "PREPARO",
      "2040": "TRATOS CULTURAIS",
      "6003": "FERTIRRIGACAO",
      "1081": "TRATOS CULTURAIS",
      "3079": "PREPARO",
      "1078": "HERBICIDA",
      "1050": "FERTIRRIGACAO",
      "1047": "TRATOS CULTURAIS",
      "1102": "FERTIRRIGACAO",
      "1084": "-",
      "1087": "PREPARO",
      "1079": "HERBICIDA",
      "1021": "PREPARO",
      "4016": "BIOMASSA",
      "3083": "FERTIRRIGACAO",
      "2021": "PREPARO",
      "4022": "BIOMASSA",
      "1037": "TRATOS CULTURAIS",
      "1107": "HERBICIDA",
      "1045": "PREPARO",
      "3049": "BIOMASSA",
      "3019": "PREPARO",
      "9999": "PREPARO"
    },
    "ultimaAlteracao": "2026-09-10T14:04:40.001164"
  },
  "ultimaSincronizacao": "2026-09-10 15:53:34"
};